name: 'klaviyo_integration_tests'
version: '1.1.1'
config-version: 2
profile: 'integration_tests'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

vars:
  klaviyo_schema: klaviyo_integration_tests
  klaviyo: 
    klaviyo_campaign_identifier: "campaign"
    klaviyo_event_identifier: "event"
    klaviyo_flow_identifier: "flow"
    klaviyo_integration_identifier: "integration"
    klaviyo_person_identifier: "person"
    klaviyo_metric_identifier: "metric"

models:
  +schema: "klaviyo_{{ var('directed_schema','dev') }}"

seeds:
  +docs:
    show: False
  klaviyo_integration_tests:
    +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    person:
      +column_types:
        PHONE_NUMBER: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    flow:
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    event:
      +column_types:
        PROPERTY_ATTRIBUTION: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar(65535)' }}"

flags:
  send_anonymous_usage_stats: False
  use_colors: True